package github

import (
	"context"
	"fmt"
	"os"
	"reflect"
	"testing"
)

func TestFindAsset(t *testing.T) {
	tests := []Asset{
		// aquasecurity/tfsec
		{
			Owner:       "aquasecurity",
			Repo:        "tfsec",
			Tag:         "v1.1.5",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/aquasecurity/tfsec/releases/download/v1.1.5/tfsec-linux-amd64",
			BinaryName:  "tfsec",
		},
		{
			Owner:       "aquasecurity",
			Repo:        "tfsec",
			Tag:         "v1.1.5",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/aquasecurity/tfsec/releases/download/v1.1.5/tfsec-darwin-amd64",
			BinaryName:  "tfsec",
		},
		{
			Owner:       "aquasecurity",
			Repo:        "tfsec",
			Tag:         "v1.1.5",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/aquasecurity/tfsec/releases/download/v1.1.5/tfsec-windows-amd64.exe",
			BinaryName:  "tfsec.exe",
		},
		// aquasecurity/trivy
		{
			Owner:       "aquasecurity",
			Repo:        "trivy",
			Tag:         "v0.17.2",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/aquasecurity/trivy/releases/download/v0.17.2/trivy_0.17.2_Linux-64bit.tar.gz",
			BinaryName:  "trivy",
		},
		{
			Owner:       "aquasecurity",
			Repo:        "trivy",
			Tag:         "v0.17.2",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/aquasecurity/trivy/releases/download/v0.17.2/trivy_0.17.2_macOS-64bit.tar.gz",
			BinaryName:  "trivy",
		},
		// argoproj/argo-workflows
		{
			Owner:       "argoproj",
			Repo:        "argo-workflows",
			Tag:         "v3.0.7",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/argoproj/argo-workflows/releases/download/v3.0.7/argo-linux-amd64.gz",
			BinaryName:  "argo",
		},
		{
			Owner:       "argoproj",
			Repo:        "argo-workflows",
			Tag:         "v3.0.7",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/argoproj/argo-workflows/releases/download/v3.0.7/argo-darwin-amd64.gz",
			BinaryName:  "argo",
		},
		{
			Owner:       "argoproj",
			Repo:        "argo-workflows",
			Tag:         "v3.0.7",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/argoproj/argo-workflows/releases/download/v3.0.7/argo-windows-amd64.gz",
			BinaryName:  "argo.exe",
		},
		// argoproj/argo-cd
		{
			Owner:       "argoproj",
			Repo:        "argo-cd",
			Tag:         "v2.0.4",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/argoproj/argo-cd/releases/download/v2.0.4/argocd-linux-amd64",
			BinaryName:  "argocd",
		},
		{
			Owner:       "argoproj",
			Repo:        "argo-cd",
			Tag:         "v2.0.4",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/argoproj/argo-cd/releases/download/v2.0.4/argocd-darwin-amd64",
			BinaryName:  "argocd",
		},
		{
			Owner:       "argoproj",
			Repo:        "argo-cd",
			Tag:         "v2.0.4",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/argoproj/argo-cd/releases/download/v2.0.4/argocd-windows-amd64.exe",
			BinaryName:  "argocd.exe",
		},
		// argoproj/argo-rollouts
		{
			Owner:       "argoproj",
			Repo:        "argo-rollouts",
			Tag:         "v0.9.0",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/argoproj/argo-rollouts/releases/download/v0.9.0/kubectl-argo-rollouts-linux-amd64",
			BinaryName:  "kubectl-argo-rollouts",
		},
		{
			Owner:       "argoproj",
			Repo:        "argo-rollouts",
			Tag:         "v0.9.0",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/argoproj/argo-rollouts/releases/download/v0.9.0/kubectl-argo-rollouts-darwin-amd64",
			BinaryName:  "kubectl-argo-rollouts",
		},
		// aws/amazon-ec2-instance-selector
		{
			Owner:       "aws",
			Repo:        "amazon-ec2-instance-selector",
			Tag:         "v2.0.2",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/aws/amazon-ec2-instance-selector/releases/download/v2.0.2/ec2-instance-selector-linux-amd64",
			BinaryName:  "ec2-instance-selector",
		},
		{
			Owner:       "aws",
			Repo:        "amazon-ec2-instance-selector",
			Tag:         "v2.0.2",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/aws/amazon-ec2-instance-selector/releases/download/v2.0.2/ec2-instance-selector-darwin-amd64",
			BinaryName:  "ec2-instance-selector",
		},
		{
			Owner:       "aws",
			Repo:        "amazon-ec2-instance-selector",
			Tag:         "v2.0.2",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/aws/amazon-ec2-instance-selector/releases/download/v2.0.2/ec2-instance-selector-windows-amd64",
			BinaryName:  "ec2-instance-selector.exe",
		},
		// buildpacks/pack
		{
			Owner:       "buildpacks",
			Repo:        "pack",
			Tag:         "v0.19.0",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/buildpacks/pack/releases/download/v0.19.0/pack-v0.19.0-linux.tgz",
			BinaryName:  "pack",
		},
		{
			Owner:       "buildpacks",
			Repo:        "pack",
			Tag:         "v0.19.0",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/buildpacks/pack/releases/download/v0.19.0/pack-v0.19.0-macos.tgz",
			BinaryName:  "pack",
		},
		{
			Owner:       "buildpacks",
			Repo:        "pack",
			Tag:         "v0.19.0",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/buildpacks/pack/releases/download/v0.19.0/pack-v0.19.0-windows.zip",
			BinaryName:  "pack.exe",
		},
		// CircleCI-Public/circleci-cli
		{
			Owner:       "CircleCI-Public",
			Repo:        "circleci-cli",
			Tag:         "v0.1.8764",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/CircleCI-Public/circleci-cli/releases/download/v0.1.8764/circleci-cli_0.1.8764_linux_amd64.tar.gz",
			BinaryName:  "circleci",
		},
		{
			Owner:       "CircleCI-Public",
			Repo:        "circleci-cli",
			Tag:         "v0.1.8764",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/CircleCI-Public/circleci-cli/releases/download/v0.1.8764/circleci-cli_0.1.8764_darwin_amd64.tar.gz",
			BinaryName:  "circleci",
		},
		{
			Owner:       "CircleCI-Public",
			Repo:        "circleci-cli",
			Tag:         "v0.1.8764",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/CircleCI-Public/circleci-cli/releases/download/v0.1.8764/circleci-cli_0.1.8764_windows_amd64.zip",
			BinaryName:  "circleci.exe",
		},
		// cli/cli
		{
			Owner:       "cli",
			Repo:        "cli",
			Tag:         "v1.12.0",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/cli/cli/releases/download/v1.12.0/gh_1.12.0_linux_amd64.tar.gz",
			BinaryName:  "gh",
		},
		{
			Owner:       "cli",
			Repo:        "cli",
			Tag:         "v1.12.0",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/cli/cli/releases/download/v1.12.0/gh_1.12.0_macOS_amd64.tar.gz",
			BinaryName:  "gh",
		},
		{
			Owner:       "cli",
			Repo:        "cli",
			Tag:         "v1.12.0",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/cli/cli/releases/download/v1.12.0/gh_1.12.0_windows_amd64.zip",
			BinaryName:  "gh.exe",
		},
		// docker/compose
		{
			Owner:       "docker",
			Repo:        "compose",
			Tag:         "1.25.4",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64",
			BinaryName:  "docker-compose",
		},
		{
			Owner:       "docker",
			Repo:        "compose",
			Tag:         "1.25.4",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Darwin-x86_64",
			BinaryName:  "docker-compose",
		},
		{
			Owner:       "docker",
			Repo:        "compose",
			Tag:         "1.25.4",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Windows-x86_64.exe",
			BinaryName:  "docker-compose.exe",
		},
		// docker/machine
		{
			Owner:       "docker",
			Repo:        "machine",
			Tag:         "v0.16.2",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-Linux-x86_64",
			BinaryName:  "docker-machine",
		},
		{
			Owner:       "docker",
			Repo:        "machine",
			Tag:         "v0.16.2",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-Darwin-x86_64",
			BinaryName:  "docker-machine",
		},
		{
			Owner:       "docker",
			Repo:        "machine",
			Tag:         "v0.16.2",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-Windows-x86_64.exe",
			BinaryName:  "docker-machine.exe",
		},
		// docker/scan-cli-plugin
		{
			Owner:       "docker",
			Repo:        "scan-cli-plugin",
			Tag:         "v0.17.0",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/docker/scan-cli-plugin/releases/download/v0.17.0/docker-scan_linux_amd64",
			BinaryName:  "docker-scan",
		},
		{
			Owner:       "docker",
			Repo:        "scan-cli-plugin",
			Tag:         "v0.17.0",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/docker/scan-cli-plugin/releases/download/v0.17.0/docker-scan_darwin_amd64",
			BinaryName:  "docker-scan",
		},
		{
			Owner:       "docker",
			Repo:        "scan-cli-plugin",
			Tag:         "v0.17.0",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/docker/scan-cli-plugin/releases/download/v0.17.0/docker-scan_windows_amd64.exe",
			BinaryName:  "docker-scan.exe",
		},
		// fluxcd/flux2
		{
			Owner:       "fluxcd",
			Repo:        "flux2",
			Tag:         "v0.8.0",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/fluxcd/flux2/releases/download/v0.8.0/flux_0.8.0_linux_amd64.tar.gz",
			BinaryName:  "flux",
		},
		{
			Owner:       "fluxcd",
			Repo:        "flux2",
			Tag:         "v0.8.0",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/fluxcd/flux2/releases/download/v0.8.0/flux_0.8.0_darwin_amd64.tar.gz",
			BinaryName:  "flux",
		},
		{
			Owner:       "fluxcd",
			Repo:        "flux2",
			Tag:         "v0.8.0",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/fluxcd/flux2/releases/download/v0.8.0/flux_0.8.0_windows_amd64.zip",
			BinaryName:  "flux.exe",
		},
		// goodwithtech/dockle
		{
			Owner:       "goodwithtech",
			Repo:        "dockle",
			Tag:         "v0.3.1",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/goodwithtech/dockle/releases/download/v0.3.1/dockle_0.3.1_Linux-64bit.tar.gz",
			BinaryName:  "dockle",
		},
		{
			Owner:       "goodwithtech",
			Repo:        "dockle",
			Tag:         "v0.3.1",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/goodwithtech/dockle/releases/download/v0.3.1/dockle_0.3.1_macOS-64bit.tar.gz",
			BinaryName:  "dockle",
		},
		{
			Owner:       "goodwithtech",
			Repo:        "dockle",
			Tag:         "v0.3.1",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/goodwithtech/dockle/releases/download/v0.3.1/dockle_0.3.1_Windows-64bit.zip",
			BinaryName:  "dockle.exe",
		},
		// gravitational/teleport
		{
			Owner:       "gravitational",
			Repo:        "teleport",
			Tag:         "v8.1.0",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://get.gravitational.com/teleport-v8.1.0-linux-amd64-bin.tar.gz",
			BinaryName:  "tsh",
		},
		{
			Owner:       "gravitational",
			Repo:        "teleport",
			Tag:         "v8.1.0",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://get.gravitational.com/teleport-v8.1.0-darwin-amd64-bin.tar.gz",
			BinaryName:  "tsh",
		},
		{
			Owner:       "gravitational",
			Repo:        "teleport",
			Tag:         "v8.1.0",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://get.gravitational.com/teleport-v8.1.0-windows-amd64-bin.zip",
			BinaryName:  "tsh.exe",
		},
		// hashicorp/terraform
		{
			Owner:       "hashicorp",
			Repo:        "terraform",
			Tag:         "v0.12.20",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_linux_amd64.zip",
			BinaryName:  "terraform",
		},
		{
			Owner:       "hashicorp",
			Repo:        "terraform",
			Tag:         "v0.12.20",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_darwin_amd64.zip",
			BinaryName:  "terraform",
		},
		{
			Owner:       "hashicorp",
			Repo:        "terraform",
			Tag:         "v0.12.20",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_windows_amd64.zip",
			BinaryName:  "terraform.exe",
		},
		// helm/helm
		{
			Owner:       "helm",
			Repo:        "helm",
			Tag:         "v3.1.0",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://get.helm.sh/helm-v3.1.0-linux-amd64.tar.gz",
			BinaryName:  "helm",
		},
		{
			Owner:       "helm",
			Repo:        "helm",
			Tag:         "v3.1.0",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://get.helm.sh/helm-v3.1.0-darwin-amd64.tar.gz",
			BinaryName:  "helm",
		},
		{
			Owner:       "helm",
			Repo:        "helm",
			Tag:         "v3.1.0",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://get.helm.sh/helm-v3.1.0-windows-amd64.zip",
			BinaryName:  "helm.exe",
		},
		// istio/istio
		{
			Owner:       "istio",
			Repo:        "istio",
			Tag:         "1.6.0",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/istio/istio/releases/download/1.6.0/istioctl-1.6.0-linux-amd64.tar.gz",
			BinaryName:  "istioctl",
		},
		{
			Owner:       "istio",
			Repo:        "istio",
			Tag:         "1.6.0",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/istio/istio/releases/download/1.6.0/istioctl-1.6.0-osx.tar.gz",
			BinaryName:  "istioctl",
		},
		{
			Owner:       "istio",
			Repo:        "istio",
			Tag:         "1.6.0",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/istio/istio/releases/download/1.6.0/istioctl-1.6.0-win.zip",
			BinaryName:  "istioctl.exe",
		},
		// mikefarah/yq
		{
			Owner:       "mikefarah",
			Repo:        "yq",
			Tag:         "v4.7.1",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/mikefarah/yq/releases/download/v4.7.1/yq_linux_amd64",
			BinaryName:  "yq",
		},
		{
			Owner:       "mikefarah",
			Repo:        "yq",
			Tag:         "v4.7.1",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/mikefarah/yq/releases/download/v4.7.1/yq_darwin_amd64",
			BinaryName:  "yq",
		},
		{
			Owner:       "mikefarah",
			Repo:        "yq",
			Tag:         "v4.7.1",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/mikefarah/yq/releases/download/v4.7.1/yq_windows_amd64.exe",
			BinaryName:  "yq.exe",
		},
		// mozilla/sops
		{
			Owner:       "mozilla",
			Repo:        "sops",
			Tag:         "v3.5.0",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/mozilla/sops/releases/download/v3.5.0/sops-v3.5.0.linux",
			BinaryName:  "sops",
		},
		{
			Owner:       "mozilla",
			Repo:        "sops",
			Tag:         "v3.5.0",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/mozilla/sops/releases/download/v3.5.0/sops-v3.5.0.darwin",
			BinaryName:  "sops",
		},
		{
			Owner:       "mozilla",
			Repo:        "sops",
			Tag:         "v3.5.0",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/mozilla/sops/releases/download/v3.5.0/sops-v3.5.0.exe",
			BinaryName:  "sops.exe",
		},
		// open-policy-agent/conftest
		{
			Owner:       "open-policy-agent",
			Repo:        "conftest",
			Tag:         "v0.21.0",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/open-policy-agent/conftest/releases/download/v0.21.0/conftest_0.21.0_Linux_x86_64.tar.gz",
			BinaryName:  "conftest",
		},
		{
			Owner:       "open-policy-agent",
			Repo:        "conftest",
			Tag:         "v0.21.0",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/open-policy-agent/conftest/releases/download/v0.21.0/conftest_0.21.0_Darwin_x86_64.tar.gz",
			BinaryName:  "conftest",
		},
		{
			Owner:       "open-policy-agent",
			Repo:        "conftest",
			Tag:         "v0.21.0",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/open-policy-agent/conftest/releases/download/v0.21.0/conftest_0.21.0_Windows_x86_64.zip",
			BinaryName:  "conftest.exe",
		},
		// open-policy-agent/opa
		{
			Owner:       "open-policy-agent",
			Repo:        "opa",
			Tag:         "v0.29.4",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/open-policy-agent/opa/releases/download/v0.29.4/opa_linux_amd64",
			BinaryName:  "opa",
		},
		{
			Owner:       "open-policy-agent",
			Repo:        "opa",
			Tag:         "v0.29.4",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/open-policy-agent/opa/releases/download/v0.29.4/opa_darwin_amd64",
			BinaryName:  "opa",
		},
		{
			Owner:       "open-policy-agent",
			Repo:        "opa",
			Tag:         "v0.29.4",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/open-policy-agent/opa/releases/download/v0.29.4/opa_windows_amd64.exe",
			BinaryName:  "opa.exe",
		},
		// protocolbuffers/protobuf
		{
			Owner:       "protocolbuffers",
			Repo:        "protobuf",
			Tag:         "v3.11.4",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip",
			BinaryName:  "protoc",
		},
		{
			Owner:       "protocolbuffers",
			Repo:        "protobuf",
			Tag:         "v3.11.4",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-osx-x86_64.zip",
			BinaryName:  "protoc",
		},
		{
			Owner:       "protocolbuffers",
			Repo:        "protobuf",
			Tag:         "v3.11.4",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-win64.zip",
			BinaryName:  "protoc.exe",
		},
		// starship/starship
		{
			Owner:       "starship",
			Repo:        "starship",
			Tag:         "v0.47.0",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/starship/starship/releases/download/v0.47.0/starship-x86_64-unknown-linux-gnu.tar.gz",
			BinaryName:  "starship",
		},
		{
			Owner:       "starship",
			Repo:        "starship",
			Tag:         "v0.47.0",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/starship/starship/releases/download/v0.47.0/starship-x86_64-apple-darwin.tar.gz",
			BinaryName:  "starship",
		},
		{
			Owner:       "starship",
			Repo:        "starship",
			Tag:         "v0.47.0",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/starship/starship/releases/download/v0.47.0/starship-x86_64-pc-windows-msvc.zip",
			BinaryName:  "starship.exe",
		},
		// viaduct-ai/kustomize-sops
		{
			Owner:       "viaduct-ai",
			Repo:        "kustomize-sops",
			Tag:         "v2.3.3",
			Goos:        "linux",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/viaduct-ai/kustomize-sops/releases/download/v2.3.3/ksops_2.3.3_Linux_x86_64.tar.gz",
			BinaryName:  "ksops",
		},
		{
			Owner:       "viaduct-ai",
			Repo:        "kustomize-sops",
			Tag:         "v2.3.3",
			Goos:        "darwin",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/viaduct-ai/kustomize-sops/releases/download/v2.3.3/ksops_2.3.3_Darwin_x86_64.tar.gz",
			BinaryName:  "ksops",
		},
		{
			Owner:       "viaduct-ai",
			Repo:        "kustomize-sops",
			Tag:         "v2.3.3",
			Goos:        "windows",
			Goarch:      "amd64",
			DownloadURL: "https://github.com/viaduct-ai/kustomize-sops/releases/download/v2.3.3/ksops_2.3.3_Windows_x86_64.tar.gz",
			BinaryName:  "ksops.exe",
		},
	}

	ctx := context.Background()
	client, err := NewClient(ctx, os.Getenv("GITHUB_TOKEN"))
	if err != nil {
		t.Fatal(err)
	}

	for _, tt := range tests {
		name := fmt.Sprintf("%s-%s-%s-%s-%s", tt.Owner, tt.Repo, tt.Tag, tt.Goos, tt.Goarch)
		t.Run(name, func(t *testing.T) {
			keyword := fmt.Sprintf("%s/%s", tt.Owner, tt.Repo)
			asset, err := client.FindAsset(ctx, keyword, tt.Tag, tt.Goos, tt.Goarch)
			if err != nil {
				t.Fatal(err)
			}
			if !reflect.DeepEqual(tt, asset) {
				t.Fatalf("Expected is %v but actual is %v", tt, asset)
			}
		})
	}
}
