name: Test
on:
  push:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: make test
        env:
          GOOS: linux
          GOARCH: amd64
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
